name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Skip if release commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == 'chore(release):'* ]]; then
            echo "Skipping bump job for release commit"
            exit 0
          fi

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.ADMIN_TOKEN }}"

      - name: Install Commitizen
        run: pip install commitizen

      - name: Bump version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cz bump --yes --changelog || true

      - name: Push changes and tags
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git push origin main --follow-tags
          else
            echo "No changes to push (no bump needed)."
          fi
