name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and update changelog"
    steps:
      - name: Skip if release commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == 'chore(release):'* ]]; then
            echo "Skipping bump job for release commit"
            exit 0
          fi

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.ADMIN_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
          debug: true

      - name: Push changes and tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git push origin main --follow-tags
          else
            echo "No changes to push (no bump needed)."
          fi
